name: Expo Auto Update
on:
  push:
    branches:
      - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Expo környezet beállítása
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: Függőségek telepítése
        working-directory: ./app
        run: npm install

      - name: CLI jogosultságok javítása
        working-directory: ./app
        run: |
          find node_modules/.bin -type f | xargs chmod +x 2>/dev/null || true
          find node_modules/expo/bin -type f | xargs chmod +x 2>/dev/null || true
          find node_modules/react-native/sdks -type f | xargs chmod +x 2>/dev/null || true

      - name: Frissítés küldése az Expoba
        working-directory: ./app
        env:
          CI: 1
        run: eas update --auto --non-interactive
