name: Expo Auto Update
on:
  push:
    branches:
      - main # Vagy master, ha az a fő ág neve

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # Kitöröltük a cache sort, így nem fogja hiányolni a lock fájlt

      - name: Expo környezet beállítása
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Függőségek (Dependencies) telepítése
        run: npm install # 'npm ci' helyett 'npm install'-t használunk, ez legyártja magának a szerveren

      - name: Frissítés küldése az Expoba
        run: eas update --auto --non-interactive
